// Auto-generated by /ajouteanalytics — PostHog scene tracking helper
export async function trackScene(sceneName: string, opts?: { title?: string; categorie?: string; source?: string }) {
  if (typeof window === "undefined") return;
  try {
    const posthog = (await import("posthog-js")).default;
    if (!posthog.__loaded) return;
    const source = opts?.source ?? "menu";
    posthog.capture("$pageview", { scene: sceneName, title: opts?.title });
    posthog.capture("scene_view", {
      scene: sceneName,
      title: opts?.title,
      categorie: opts?.categorie,
      source,
    });
    posthog.capture("hotspot_click", {
      scene: sceneName,
      title: opts?.title,
      source,
    });
  } catch {}
}
